version: '2'

volumes:
  # MySQL Data
  boilerplate-database-data:
    driver: local

  # Redis Data
  boilerplate-redis-data:
    driver: local

services:

  # MySQL (5.7)
  database:
    image: ambientum/mysql:5.7
    container_name: boilerplate-database
    volumes:
      - boilerplate-database-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: boilerplate-redis
    command: --appendonly yes
    volumes:
      - boilerplate-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Ngnix)
  app:
    image: ambientum/php:7.1-nginx
    container_name: boilerplate-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - database
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.1
    container_name: boilerplate-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - database
      - cache
